### ISSUE TITLE
有内存泄漏

### ISSUE THREAD

**Issue by cowboyfzl** [bingozb/DKNetworking#11]
有内存泄漏可以处理吗

**Comment by bingozb** [comment]
@cowboyfzl 确定是 DKN 的内存泄漏吗？

![noleak](https://ws1.sinaimg.cn/large/0067zF04ly1fr4wwds1cjj31280czwh1.jpg)

我这边调试并没有发现内存泄漏的问题，而且已经在许多线上项目使用，也都没有发现内存泄漏。请检查是否是你项目中其它地方导致的。

如果你分析后确定是 DKN 的内存泄漏问题，欢迎再打开 issues ，贴上 instruments 等工具的截图进行反馈。
