### ISSUE TITLE
DELETE How to pass parameters in form as POST

### ISSUE THREAD

**Issue by alizbeo** [bingozb/DKNetworking#5]
I want to pass parameters in body for method DELETE, how to do that?

**Comment by bingozb** [comment]
@alizbeo You can just call this: + [DKNetworking DELETE: parameters:];

eg.:
```objc
[DKNetworking DELETE:@"user/login" parameters:@{@"name":@"Bingo"} callback:^(DKNetworkRequest *request, DKNetworkResponse *response) {
    // ...
}];
```

And if you use RAC, you can also try this:
```objc
RACSignal *signal = DKNetworkManager.delete(@"user/login").params(@{@"name":@"Bingo"}).executeSignal;
[signal subscribeNext:^(RACTuple *x) {
    // ...
}];
```

**Comment by JTL1992** [comment]
@bingozb no send in body but in URL.

**Comment by bingozb** [comment]
@alizbeo @JTL1992 OK, I see your problem.

You need to do is change HTTP methods, that encode parameters as a query string (by default GET, HEAD, and DELETE). Request serializer has **HTTPMethodsEncodingParametersInURI** property for that. 

You can find this in AFNetworking -> AFURLRequestSerialization.m, line 245.

```objc
// HTTP Method Definitions; see http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html
self.HTTPMethodsEncodingParametersInURI = [NSSet setWithObjects:@"GET", @"HEAD", @"DELETE", nil];
```

If you want to send params in body, just to set with **GET, HEAD**, without **DELETE**.
I will provide a method to setup it and release DKN **v1.4.1** today. And then you can call this:

```
[DKNetworking setupSessionManager:^(DKNetworkSessionManager *sessionManager) {
        sessionManager.requestSerializer.HTTPMethodsEncodingParametersInURI = [NSSet setWithObjects:@"GET", @"HEAD", nil];
}];
```
